server:
  port: 9037
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/search_engine
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
user-agent:
  options:
    name: CheloBotLightning
    referrer: http://www.google.com





